name: main branch PR build

on:
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/main-pr-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Node 24.0.2
        uses: actions/setup-node@v4
        with:
          node-version: 24.0.2
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm run build-storybook
