name: main branch PR build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with Node 24.0.2
      uses: actions/setup-node@v4
      with:
        node-version: 24.0.2
        cache: 'npm'
    - run: npm run build
